version: "3.8"
services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  clickhouse:
    image: clickhouse/clickhouse-server
    #environment:
    #- CLICKHOUSE_USER=clickhouse
    #- CLICKHOUSE_PASSWORD=clickhouse
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

volumes:
  db:
    driver: local
