version: "3.8"
services:
  postgres:
    image: bitnami/postgresql:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - shared-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.3.2
    #environment:
    #- CLICKHOUSE_USER=clickhouse
    #- CLICKHOUSE_PASSWORD=clickhouse
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

  ssh_server:
    image: linuxserver/openssh-server
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER_NAME=remoteuser
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=testpass
      - PUBLIC_KEY_FILE=/home/remoteuser/.ssh/ssh_test_rsa.pub
      - LOG_STDOUT=true
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    volumes:
      - ~/.ssh/ssh_tunnel_test:/home/remoteuser/.ssh
    depends_on:
      - postgres
      - clickhouse
    networks:
      - shared-network

volumes:
  db:
    driver: local

networks:
  shared-network:
    driver: bridge
